spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/fb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  mail:
    host: smtp.qq.com
    port: 587
    username: 1532328736@qq.com
    password: xzvxteuatdxmhjbf
    default-encoding: UTF-8

    # 配置SMTP协议的加密方法，这里使用STARTTLS
    properties:
      mail:
        smtp:
          starttls:
            enable: true
        auth: true
server:
  port: 10086